RIBN-661
Topl/ribn pull request #268
Opened 2023-01-31 05:43 UTC by Brianspha

This removes Topl DApp URLs from being injected

## Description

This remove the default Topl DApps from being injected with each init of the wallet

Fixes #RIBN-661

## Backend

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] New and existing unit tests pass locally with my changes
-   [x] I have checked my code and corrected any misspellings

2023-01-31 19:03 UTC, KalervoHyyppa requested changes

2023-01-31 19:03 UTC, KalervoHyyppa commented on lib/main.dart
> +  await Redux.initStore(initTestStore: false);
Can you revert back to detect kDebugMode

2023-01-31 20:51 UTC, Brianspha commented on lib/main.dart
> +  await Redux.initStore(initTestStore: false);
For sure this doesnt work with chrome extension though since it builds in release

2023-02-01 14:52 UTC, KalervoHyyppa approved these changes
LGTM

2023-02-01 14:53 UTC, merged