Settings refactor
Topl/ribn pull request #286
Opened 2023-02-14 14:31 UTC by ultimaterex

2023-02-20 19:17 UTC, KalervoHyyppa requested changes
Wait to merge until [RIBN-673](https://github.com/Topl/ribn/pull/287) is merged

2023-02-22 16:32 UTC, KalervoHyyppa requested changes
Look at comments

2023-02-22 16:32 UTC, KalervoHyyppa commented on lib/presentation/login/login_page.dart
> +    }, [biometrics]);
Is `[biometrics]` needed? I believe it should be just `[]`. Currently, whenever `biometrics` changes, it will rerun `_checkBiometrics `

2023-02-22 16:32 UTC, KalervoHyyppa commented on lib/presentation/onboarding/create_wallet/wallet_info_checklist_page.dart
> +  Future<void> runBiometrics(isBioSupported, ref) =>
Changing this function broke the page. Getting error `Cannot listen to inherited widgets inside HookState.initState`

2023-02-22 16:32 UTC, KalervoHyyppa commented on lib/presentation/settings/sections/biometrics_section.dart
> +  Future<void> runBiometrics(
Something about this function is not working. It takes 2 toggles on my phone (Pixel 7), the black screens are fingerprint reading screens.

https://user-images.githubusercontent.com/51681634/220688333-8a6a88dd-5c5b-444d-927a-b528fc2ffeb5.mp4

2023-02-22 16:32 UTC, KalervoHyyppa commented on lib/providers/biometrics_provider.dart
> +  final localAuthentication = ref.read(localAuthenticationProvider).call();
This should just be `ref.read(localAuthenticationProvider)()`

2023-02-22 16:32 UTC, KalervoHyyppa commented on lib/providers/settings_page_provider.dart
> +class SettingState {
Move to its on file in `lib/models/state/`

2023-02-22 16:32 UTC, KalervoHyyppa commented on lib/presentation/settings/settings_page.dart
> +class SettingsPage extends ConsumerWidget {
Looks like `ref` is not used in this widget, should be `StatelessWidget`

2023-02-22 17:06 UTC, ultimaterex commented on lib/presentation/login/login_page.dart
> +    }, [biometrics]);
@KalervoHyyppa I used to have it without the key and it resulted in some strange behaviour where it ran once but it was too soon in the build step, i reccomend trying it out yourself

2023-02-22 17:07 UTC, ultimaterex commented on lib/presentation/settings/sections/biometrics_section.dart
> +  Future<void> runBiometrics(
Interesting, I'll have to investigate this one further

2023-03-07 17:53 UTC, KalervoHyyppa requested changes
Please run `dart format lib . -l 120` and merge dev into this branch.

2023-03-08 15:43 UTC, ultimaterex commented on lib/utils/transaction_utils.dart
> +    // Get teh receivers address
I appreciate how I fixed the typo here but not the more obvious typo of "The"

2023-03-08 17:12 UTC, KalervoHyyppa requested changes
See comments

2023-03-08 17:35 UTC, ultimaterex commented on lib/presentation/login/widgets/forget_password_link_section.dart
> +// Flutter imports:
Fixed in latest commit

2023-03-08 17:53 UTC, KalervoHyyppa approved these changes
Great work!

2023-03-08 17:53 UTC, merged