Ribn 673
Topl/ribn pull request #287
Opened 2023-02-14 21:50 UTC by KalervoHyyppa

## Description

This is a Refactor of Onboarding, adding the use of Riverpod

Fixes # (issue)

[RIBN-673](https://topl.atlassian.net/jira/software/c/projects/RIBN/boards/5?modal=detail&selectedIssue=RIBN-673)

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings

2023-02-15 15:57 UTC, ultimaterex requested changes
Content wise, it seems solid and I have not seen any major issues. I do have a bunch of styling nitpicks, I have yet to run a physical test. I'll update you with that feedback once you've addressed my comments.

2023-02-15 15:57 UTC, ultimaterex commented on lib/utils/error_handling_utils.dart
> +Future<void> handleApiError({
I love this, would there be any added value to log a warning or something similar to the console here?

2023-02-15 15:57 UTC, ultimaterex commented on test/mocks/local_authentication_mocks.mocks.dart
> +// Mocks generated by Mockito 5.3.2 from annotations
Ditto about generated files being committed to the repo

2023-02-15 16:02 UTC, ultimaterex commented on lib/models/keychain_state.dart
>    /// Gets all supported [RibnNetwork]s.
specifically the //Todo

2023-02-15 16:03 UTC, ultimaterex commented
The linter in general is also quite unhappy about some nullable marked members that don't return values

2023-02-16 17:06 UTC, KalervoHyyppa commented on lib/presentation/onboarding/create_wallet/seed_phrase_confirmation_page.dart
> +  static const Key seedPhraseConfirmationConfirmationButtonKey =
I generally like to keep them in their widgets (or parent widgets) so it's easier to find where exactly they are being used vs having to search mutliple files.

2023-02-16 17:32 UTC, KalervoHyyppa commented on lib/models/keychain_state.dart
>    /// Gets all supported [RibnNetwork]s.
I've made tickets for all models to utilize freezed. [RIBN-697](https://topl.atlassian.net/browse/RIBN-697), specifically for this one. I'll remove the todo

2023-02-16 18:31 UTC, KalervoHyyppa commented
> The linter in general is also quite unhappy about some nullable marked members that don't return values

@ultimaterex Regarding analyzer, I'm seeing 2 reasons why errors are being thrown,

1. Autogenerated files have been removed, so there are errors because of that
2. ribn-toolkit needs to be updated

2023-02-17 06:06 UTC, ultimaterex commented
> > The linter in general is also quite unhappy about some nullable marked members that don't return values
> 
> @ultimaterex Regarding analyzer, I'm seeing 2 reasons why errors are being thrown,
> 
> 1. Autogenerated files have been removed, so there are errors because of that
> 2. ribn-toolkit needs to be updated

Re 1: We should make an action item to add the make gen step to the CI analyzer so that it can successfully run the tests.

2023-02-17 06:09 UTC, ultimaterex approved these changes

2023-02-17 06:09 UTC, ultimaterex commented
I've approved the style changes for this PR and will let you know how manual testing goes.

2023-02-21 15:01 UTC, Brianspha commented on lib/providers/onboarding_provider.dart
> +    final onboardingState = _generateOnboardingState(ref);
Here we could be explicit with the type of onboardingState
e.g.
final OnboardingState onboardingState = _generateOnboardingState(ref);

2023-02-21 17:03 UTC, Brianspha requested changes
Additionally, please see lines 150 on the enable_biometrics.dart page please remove the 

     ```
       const SizedBox(
              height: 15,
            ),
```

On the same file please change the font size of the heading (Enable Biometrics) to 20

2023-02-21 19:33 UTC, Brianspha approved these changes

2023-02-21 20:00 UTC, merged