Merge 0.4 to 0.5
Topl/ribn pull request #301
Opened 2023-03-06 20:43 UTC by KalervoHyyppa

## Description

This merges rc-0.4 into dev (rc-0.5)

Fixes # (issue)

[RIBN-782](https://topl.atlassian.net/jira/software/c/projects/RIBN/boards/5?modal=detail&selectedIssue=RIBN-782)

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings

2023-03-07 16:12 UTC, ultimaterex requested changes

2023-03-07 16:12 UTC, ultimaterex commented on pubspec.yaml
> +  built_value_generator: ^8.1.2
What are we using built value for that freezed doesn't do for us?

2023-03-07 21:22 UTC, KalervoHyyppa commented on lib/main.dart
> +// import 'package:ribn/platform/web/wallet.dart';
Looks like it was added by Mustafa 1.5 years ago, I'll remove

2023-03-07 21:24 UTC, KalervoHyyppa commented on pubspec.yaml
> +  built_value_generator: ^8.1.2
Not sure what this package does, must have been left over from another 0.4 PR; removing.

2023-03-07 21:49 UTC, ultimaterex approved these changes

2023-03-08 00:13 UTC, scasplte2 approved these changes
🔥

2023-03-08 14:43 UTC, merged