ANNULUS-266: Product: Wallet Assets Provider
Topl/ribn pull request #347
Opened 2023-08-28 13:11 UTC by lukorito

## Description

Implement Asset Provider

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have added screenshots

2023-08-28 19:40 UTC, KalervoHyyppa commented on lib/v2/asset_managment/providers/transactions/keychain_network_providers/assets_provider_class.dart
> +// TODO SDK - Should this even be called transactions? Maybe it should be called crypto
Clean up

2023-08-29 19:28 UTC, KalervoHyyppa requested changes
One small comment

2023-08-30 14:46 UTC, KalervoHyyppa approved these changes
Looks great

2023-08-30 15:06 UTC, berriose approved these changes

2023-08-30 15:07 UTC, merged