ANNULUS-307: Wallet: Update the next button in Stepper Screen to support form-checking
Topl/ribn pull request #351
Opened 2023-09-05 21:41 UTC by lukorito

## Description

Wallet: Update the next button in Stepper Screen to support form-checking

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
-   [x] New feature (non-breaking change which adds functionality)
## How Has This Been Tested?

Manually

## Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have added screenshots

2023-09-06 14:14 UTC, KalervoHyyppa commented on lib/v2/shared/providers/stepper_navigation_control_prover.dart
> +enum StepperNavigationControl {
instead of an enum, make a freezed class similar to `StepperScreenState`

2023-09-06 14:21 UTC, KalervoHyyppa reviewed
Add checks to the recovery seed phrase input as well

2023-09-06 14:21 UTC, KalervoHyyppa commented on lib/v2/shared/providers/stepper_navigation_control_prover.dart
> +enum StepperNavigationControl {
instead of an enum, make a freezed class similar to `StepperScreenState`

2023-09-11 21:56 UTC, KalervoHyyppa requested changes
If I type in a correct pin but then type and incorrect pin, I can still go forward. Also can go forward on the confirm pin page wihtout type pin as well. See video

https://github.com/Topl/ribn/assets/51681634/f03a58f4-e7e4-47db-99ea-9ed5de0a84d1

2023-09-11 21:56 UTC, KalervoHyyppa commented on lib/v2/onboarding/widgets/pages/create_pin_page.dart
> +    useEffect(() {
please add a

```
return (){
    null
}
```

to fix build errors

2023-09-13 19:29 UTC, lukorito commented
> If I type in a correct pin but then type and incorrect pin, I can still go forward. Also can go forward on the confirm pin page wihtout type pin as well. See video
> 
>  screen-20230911-155144.mp4

Fixed this as well

2023-09-16 13:53 UTC, KalervoHyyppa approved these changes
lgtm

2023-09-19 20:41 UTC, merged